### ISSUE TITLE
Make lab display name as optional in Lab descriptor.json 

### ISSUE THREAD

**Issue by ravikiran2020** [virtual-labs/ph3-lab-mgmt#220]
**Description:**
Currently, there is an issue with the validation of the "lab_display_name" field in the "lab-descriptor.json" file. The "lab_display_name" field should be optional, allowing users to provide a display name for the lab if desired. However, the validation process enforces this field as mandatory, causing an error during the lab hosting process if the "lab_display_name" field is not provided.

**Steps to Reproduce:**

Create a "lab-descriptor.json" file with all the necessary properties for lab configuration, excluding the "lab_display_name" field.
Attempt to initiate the hosting process using the appropriate command or tool, referencing the "lab-descriptor.json" file.
Expected Behavior:
The hosting process should initiate successfully, even if the "lab_display_name" field is not provided in the "lab-descriptor.json" file. If the "lab_display_name" field is omitted, a default display name or no display name should be used.

**Actual Behavior:**
The hosting process fails with an error indicating that the "lab_display_name" field is missing or required.

**Impact:**
This issue prevents labs from being hosted if the "lab_display_name" field is not included in the "lab-descriptor.json" file, even though the field is intended to be optional. This inconsistency between design and implementation can lead to confusion and unnecessary hurdles for users who do not wish to provide a custom display name for their labs.

**Proposed Solution:**
Review the validation logic related to the "lab_display_name" field in the hosting process. Adjust the validation to treat the "lab_display_name" field as optional, allowing the hosting process to proceed even if the field is not present in the "lab-descriptor.json" file.

**Comment by Vanshika-Dhingra** [comment]
in file labDescSchema.json modify 
        "lab_display_name": {"type": "string"} 
        to
       "lab_display_name": {
            "type": "string",
            "default": "Default Lab Display Name"
        },
